Exclude testing with scipy in the env with python 3.9 (#2583)
The PR excludes running scipy relating tests from the scope, because
there is the scipy import issue:
```bash
  File "/home/runner/miniconda3/envs/test/lib/python3.9/site-packages/dpctl/__init__.py", line 51, in <module>
    from ._sycl_queue import (
  File "dpctl/_sycl_queue.pyx", line 1, in init dpctl._sycl_queue
  File "/home/runner/miniconda3/envs/test/lib/python3.9/site-packages/dpctl/memory/__init__.py", line 31, in <module>
    from ._memory import (
  File "dpctl/memory/_memory.pyx", line 69, in init dpctl.memory._memory
  File "/home/runner/miniconda3/envs/test/lib/python3.9/site-packages/numpy/__init__.py", line 155, in <module>
    from . import fft
  File "/home/runner/miniconda3/envs/test/lib/python3.9/site-packages/numpy/fft/__init__.py", line 215, in <module>
    import mkl_fft.interfaces.numpy_fft as _nfft
  File "/home/runner/miniconda3/envs/test/lib/python3.9/site-packages/mkl_fft/__init__.py", line 45, in <module>
    import mkl_fft.interfaces  # isort: skip
  File "/home/runner/miniconda3/envs/test/lib/python3.9/site-packages/mkl_fft/interfaces/__init__.py", line 29, in <module>
    import scipy.fft
  File "/home/runner/miniconda3/envs/test/lib/python3.9/site-packages/scipy/__init__.py", line 110, in <module>
    __all__.remove('linalg')
ValueError: list.remove(x): x not in list
```
when installing the packages from
`https://software.repos.intel.com/python/conda/` channel.

The support of python 3.9 for scipy was stopped to upload there for a
long time ago and the latest available is scipy 1.8.1 which is too old
and has the import issue.