Pin `libxml2` version to 2.13.7 (#2409)
This PR pins `libxml2` version to `2.13.7` due to libs dependency issue
with `2.14.0` version as reported on
[#146](https://github.com/conda-forge/libxml2-feedstock/issues/146).

Without that change the conda package can not be build through GitHub
action, since `conda-build` raises error:
```python
Traceback (most recent call last):
  File "C:\Users\runneradmin\miniconda3\envs\build\Scripts\conda-build-script.py", line 6, in <module>
    from conda_build.cli.main_build import execute
  File "C:\Users\runneradmin\miniconda3\envs\build\Lib\site-packages\conda_build\cli\main_build.py", line 19, in <module>
    from .. import api, build, source, utils
  File "C:\Users\runneradmin\miniconda3\envs\build\Lib\site-packages\conda_build\api.py", line [24](https://github.com/IntelPython/dpnp/actions/runs/14267019048/job/39991206345#step:8:25), in <module>
    from .config import DEFAULT_PREFIX_LENGTH as _prefix_length
  File "C:\Users\runneradmin\miniconda3\envs\build\Lib\site-packages\conda_build\config.py", line 28, in <module>
    from .utils import (
  File "C:\Users\runneradmin\miniconda3\envs\build\Lib\site-packages\conda_build\utils.py", line 51, in <module>
    import libarchive
  File "C:\Users\runneradmin\miniconda3\envs\build\Lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\runneradmin\miniconda3\envs\build\Lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\runneradmin\miniconda3\envs\build\Lib\site-packages\libarchive\ffi.py", line [26](https://github.com/IntelPython/dpnp/actions/runs/14267019048/job/39991206345#step:8:27), in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\build\Lib\ctypes\__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\miniconda3\envs\build\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 1[27](https://github.com/IntelPython/dpnp/actions/runs/14267019048/job/39991206345#step:8:28)] The specified procedure could not be found
```
Here is a
[link](https://github.com/IntelPython/dpnp/actions/runs/14267019048/job/39991206345)
to the full log with the error. 073a86ce334d4e6fcf94b1b8c2ea76818277daf9