Remove cython pinning to `< 3.1` (#2443)
This PR reverts cython pinning added in #2441 which was added to unblock
CI due to compilation error:
```bash
$SRC_DIR/_skbuild/linux-x86_64-3.9/cmake-build/dpnp/dpnp_utils/dpnp_algo_utils.cxx:28898:36: error: use of undeclared identifier '__pyx_convert__to_py___pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc'; did you mean '__pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc'?
 28898 |   __Pyx_TraceReturnCValue(__pyx_r, __pyx_convert__to_py___pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc, 21, 0, __PYX_ERR(0, 466, __pyx_L1_error));
       |                                    ^
$SRC_DIR/_skbuild/linux-x86_64-3.9/cmake-build/dpnp/dpnp_utils/dpnp_algo_utils.cxx:2104:89: note: '__pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc' declared here
 2104 | typedef struct __pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc __pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc;
      |                                                                                         ^
$SRC_DIR/_skbuild/linux-x86_64-3.9/cmake-build/dpnp/dpnp_utils/dpnp_algo_utils.cxx:28898:36: error: use of undeclared identifier '__pyx_convert__to_py___pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc'; did you mean '__pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc'?
 28898 |   __Pyx_TraceReturnCValue(__pyx_r, __pyx_convert__to_py___pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc, 21, 0, __PYX_ERR(0, 466, __pyx_L1_error));
       |                                    ^
$SRC_DIR/_skbuild/linux-x86_64-3.9/cmake-build/dpnp/dpnp_utils/dpnp_algo_utils.cxx:2104:89: note: '__pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc' declared here
 2104 | typedef struct __pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc __pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc;
      |                                                                                         ^
2 errors generated.
``` d75c842f69c492c8fd58fb52d2a26dfb70286722