fix issues when running tests with all integer dtypes on GPU w/o support for fp64 (#2430)
The following tests fails when running the test suite with all integer
dtypes included on a GPU device that does not support fp64.

FAILED dpnp/tests/test_linalg.py::TestCond::test_basic
FAILED dpnp/tests/test_linalg.py::TestSvd::test_svd
FAILED dpnp/tests/test_linalg.py::TestPinv::test_pinv
FAILED
dpnp/tests/third_party/cupy/creation_tests/test_ranges.py::TestRanges::test_linspace_mixed_start_stop2
FAILED
dpnp/tests/third_party/cupy/math_tests/test_explog.py::TestExplog::test_logaddexp2
FAILED
dpnp/tests/third_party/cupy/math_tests/test_trigonometric.py::TestUnwrap::test_unwrap_1dim_with_discont_and_period
FAILED
dpnp/tests/third_party/cupy/math_tests/test_trigonometric.py::TestUnwrap::test_unwrap_1dim_with_period

This PR fixes them all. 6a81e5532988996c96bae113d5209339a3d9b067