Bump `anaconda-client` version to `1.14.1` (#2763)
This PR bumps `anaconda-client` version from 1.14.1 to 1.14.0.

Otherwise the upload step in `Conda package` workflow is failing with:
```bash
Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/upload/bin/anaconda", line 6, in <module>
    from anaconda_cli_base.cli import app
  File "/home/runner/miniconda3/envs/upload/lib/python3.13/site-packages/anaconda_cli_base/cli.py", line 229, in <module>
    load_registered_subcommands(app)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/runner/miniconda3/envs/upload/lib/python3.13/site-packages/anaconda_cli_base/plugins.py", line 282, in load_registered_subcommands
    subcommand_entry_points = _load_entry_points_for_group(PLUGIN_GROUP_NAME)
  File "/home/runner/miniconda3/envs/upload/lib/python3.13/site-packages/anaconda_cli_base/plugins.py", line 57, in _load_entry_points_for_group
    module: typer.Typer = entry_point.load()
                          ~~~~~~~~~~~~~~~~^^
  File "/home/runner/miniconda3/envs/upload/lib/python3.13/importlib/metadata/__init__.py", line 179, in load
    module = import_module(match.group('module'))
  File "/home/runner/miniconda3/envs/upload/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/upload/lib/python3.13/site-packages/binstar_client/__init__.py", line 16, in <module>
    from pkg_resources import parse_version as pv
ModuleNotFoundError: No module named 'pkg_resources'
```
Due to the latest version `82.0.0` of `setuptools` package is using now
in the env.